services:
  - type: web
    name: telegram-chess-all-in-one
    rootDir: server
    env: node
    plan: free
    buildCommand: |
      npm ci
      cd ../client
      npm ci
      npm run build
      cd ../server
      rm -rf public
      mkdir -p public
      cp -r ../client/dist/* public/
    startCommand: node src/index.js
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: JWT_SECRET
        sync: false
