services:
  - type: web
    name: telegram-chess-all-in-one
    rootDir: server
    env: node
    plan: free
    buildCommand: |
  # --- server deps ---
  npm ci || npm install --no-audit --no-fund

  # --- client build ---
  cd ../client
  npm install --no-audit --no-fund
  npm run build

  # --- copy build into server/public ---
  cd ../server
  rm -rf public
  mkdir -p public
  cp -r ../client/dist/* public/
    startCommand: node src/index.js
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
